from __future__ import annotations

import re
from pathlib import Path

from app.models.project import RenderOptions, SubtitleCue

_TIME_RE = re.compile(r"(?P<h>\d{2}):(?P<m>\d{2}):(?P<s>\d{2})[,.](?P<ms>\d{3})")


def parse_timestamp(value: str) -> float:
    match = _TIME_RE.fullmatch(value.strip())
    if not match:
        raise ValueError(f"Invalid SRT timestamp: {value}")
    parts = {key: int(number) for key, number in match.groupdict().items()}
    return parts["h"] * 3600 + parts["m"] * 60 + parts["s"] + parts["ms"] / 1000


def format_timestamp(seconds: float) -> str:
    milliseconds = max(0, round(seconds * 1000))
    hours, milliseconds = divmod(milliseconds, 3_600_000)
    minutes, milliseconds = divmod(milliseconds, 60_000)
    secs, milliseconds = divmod(milliseconds, 1000)
    return f"{hours:02}:{minutes:02}:{secs:02},{milliseconds:03}"


def format_ass_timestamp(seconds: float) -> str:
    """Formats seconds into ASS timestamp: H:MM:SS.cs (centiseconds)."""
    centiseconds = max(0, round(seconds * 100))
    hours, centiseconds = divmod(centiseconds, 360000)
    minutes, centiseconds = divmod(centiseconds, 6000)
    secs, centiseconds = divmod(centiseconds, 100)
    return f"{hours:01}:{minutes:02}:{secs:02}.{centiseconds:02}"


def wrap_vietnamese_text(text: str, max_line_chars: int = 36) -> str:
    """Intelligently wraps Vietnamese subtitle text into at most 2 balanced lines.

    Preserves full Vietnamese words and prefers splitting at natural punctuation or space.
    """
    clean = " ".join(text.replace("\r\n", " ").replace("\n", " ").split()).strip()
    if len(clean) <= max_line_chars:
        return clean

    words = clean.split()
    if len(words) <= 1:
        return clean

    # Look for punctuation marks near the center (between 30% and 70% of total length)
    mid_idx = len(clean) // 2
    best_split_pos = -1
    min_dist_to_center = float("inf")

    # Priority 1: Punctuation boundaries (. , ! ? ; : -)
    punc_matches = [m.end() for m in re.finditer(r"[,.!?;:—–-]\s+", clean)]
    for pos in punc_matches:
        dist = abs(pos - mid_idx)
        if dist < min_dist_to_center:
            min_dist_to_center = dist
            best_split_pos = pos

    # Priority 2: Space boundaries if no ideal punctuation split
    if best_split_pos == -1 or min_dist_to_center > max_line_chars // 2:
        for m in re.finditer(r"\s+", clean):
            pos = m.start()
            dist = abs(pos - mid_idx)
            if dist < min_dist_to_center:
                min_dist_to_center = dist
                best_split_pos = pos

    if best_split_pos > 0 and best_split_pos < len(clean):
        part1 = clean[:best_split_pos].strip()
        part2 = clean[best_split_pos:].strip()
        if part1 and part2:
            return part1 + r"\N" + part2

    return clean


def parse_srt(text: str) -> list[SubtitleCue]:
    normalized = text.replace("\r\n", "\n").strip()
    if not normalized:
        return []
    cues: list[SubtitleCue] = []
    for block in re.split(r"\n\s*\n", normalized):
        lines = [line.rstrip() for line in block.splitlines()]
        if len(lines) < 2:
            continue
        timing_index = 1 if lines[0].strip().isdigit() else 0
        if timing_index >= len(lines) or "-->" not in lines[timing_index]:
            continue
        start_raw, end_raw = [item.strip().split(" ")[0] for item in lines[timing_index].split("-->")]
        body = "\n".join(lines[timing_index + 1 :]).strip()
        if not body:
            continue
        cues.append(SubtitleCue(start=parse_timestamp(start_raw), end=parse_timestamp(end_raw), source_text=body))
    return cues


def to_srt(cues: list[SubtitleCue], translated: bool = True) -> str:
    blocks: list[str] = []
    for index, cue in enumerate(sorted(cues, key=lambda item: item.start), start=1):
        text = cue.translated_text if translated and cue.translated_text else cue.source_text
        blocks.append(f"{index}\n{format_timestamp(cue.start)} --> {format_timestamp(cue.end)}\n{text}")
    return "\n\n".join(blocks) + ("\n" if blocks else "")


def write_srt(path: Path, cues: list[SubtitleCue], translated: bool = True) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(to_srt(cues, translated=translated), encoding="utf-8")
    return path


def to_ass(
    cues: list[SubtitleCue],
    options: RenderOptions,
    width: int = 852,
    height: int = 480,
    translated: bool = True,
) -> str:
    """Generates a complete ASS v4.00+ subtitle file with typography styling."""
    font_name = options.font_name or "Arial"
    font_size = options.font_size or 22
    margin_v = options.margin_v or 32
    outline_w = options.outline_width or 2.5
    shadow_d = options.shadow_depth or 1.0
    font_color = options.font_color or "&H00FFFFFF"
    outline_color = options.outline_color or "&H00000000"

    header = f"""[Script Info]
; Script generated by AI Video Localizer
ScriptType: v4.00+
PlayResX: {width}
PlayResY: {height}
WrapStyle: 0
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{font_name},{font_size},{font_color},&H000000FF,{outline_color},&H80000000,-1,0,0,0,100,100,0,0,1,{outline_w},{shadow_d},2,20,20,{margin_v},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    events: list[str] = []
    # Filter out standalone noise artifacts (e.g. "10.5o", "10:50")
    noise_filter = {"10.5o", "10:50", "MILK", "MILK MILK", "IN-CN", "755135", "CN"}

    sorted_cues = sorted(cues, key=lambda item: item.start)
    for cue in sorted_cues:
        raw_text = cue.translated_text if translated and cue.translated_text else cue.source_text
        if not raw_text or raw_text.strip() in noise_filter:
            continue

        # Duration QA: ensure display duration is at least 300ms
        start_sec = cue.start
        end_sec = max(cue.end, start_sec + 0.30)

        # Smart Vietnamese line wrapping
        wrapped_text = wrap_vietnamese_text(raw_text, max_line_chars=options.max_line_chars)
        # Escape ASS special braces if needed
        ass_text = wrapped_text.replace("{", r"\{").replace("}", r"\}")

        start_str = format_ass_timestamp(start_sec)
        end_str = format_ass_timestamp(end_sec)
        events.append(f"Dialogue: 0,{start_str},{end_str},Default,,0,0,0,,{ass_text}")

    return header + "\n".join(events) + "\n"


def write_ass(
    path: Path,
    cues: list[SubtitleCue],
    options: RenderOptions,
    width: int = 852,
    height: int = 480,
    translated: bool = True,
) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(to_ass(cues, options, width, height, translated=translated), encoding="utf-8")
    return path
