from __future__ import annotations

import re
from pathlib import Path

from app.models.project import RenderOptions, SubtitleCue
from app.services.utterance_engine import (
    NOISE_SUBTITLE_PATTERNS,
    RenderSubtitleCue,
    UtteranceEngine,
    clean_vietnamese_typography,
    semantic_line_break,
)

_TIME_RE = re.compile(r"(?P<h>\d{2}):(?P<m>\d{2}):(?P<s>\d{2})[,.](?P<ms>\d{3})")


def parse_timestamp(value: str) -> float:
    match = _TIME_RE.fullmatch(value.strip())
    if not match:
        raise ValueError(f"Invalid SRT timestamp: {value}")
    parts = {key: int(number) for key, number in match.groupdict().items()}
    return parts["h"] * 3600 + parts["m"] * 60 + parts["s"] + parts["ms"] / 1000


def format_timestamp(seconds: float) -> str:
    milliseconds = max(0, round(seconds * 1000))
    hours, milliseconds = divmod(milliseconds, 3_600_000)
    minutes, milliseconds = divmod(milliseconds, 60_000)
    secs, milliseconds = divmod(milliseconds, 1000)
    return f"{hours:02}:{minutes:02}:{secs:02},{milliseconds:03}"


def format_ass_timestamp(seconds: float) -> str:
    """Formats seconds into ASS timestamp: H:MM:SS.cs (centiseconds)."""
    centiseconds = max(0, round(seconds * 100))
    hours, centiseconds = divmod(centiseconds, 360000)
    minutes, centiseconds = divmod(centiseconds, 6000)
    secs, centiseconds = divmod(centiseconds, 100)
    return f"{hours:01}:{minutes:02}:{secs:02}.{centiseconds:02}"


def wrap_vietnamese_text(text: str, max_line_chars: int = 36) -> str:
    """Wrapper function preserving semantic line breaking."""
    return semantic_line_break(text, max_line_chars=max_line_chars)


def normalize_render_cues(
    cues: list[SubtitleCue],
    safe_gap: float = 0.03,
    min_duration: float = 0.25,
    translated: bool = True,
) -> list[RenderSubtitleCue]:
    """Generates non-overlapping single-active movie subtitle cues via UtteranceEngine."""
    engine = UtteranceEngine(safe_gap=safe_gap, min_display_duration=max(0.80, min_duration))
    render_cues, _ = engine.process_cues(cues, translated=translated)
    return render_cues


def parse_srt(text: str) -> list[SubtitleCue]:
    normalized = text.replace("\r\n", "\n").strip()
    if not normalized:
        return []
    cues: list[SubtitleCue] = []
    for block in re.split(r"\n\s*\n", normalized):
        lines = [line.rstrip() for line in block.splitlines()]
        if len(lines) < 2:
            continue
        timing_index = 1 if lines[0].strip().isdigit() else 0
        if timing_index >= len(lines) or "-->" not in lines[timing_index]:
            continue
        start_raw, end_raw = [item.strip().split(" ")[0] for item in lines[timing_index].split("-->")]
        body = "\n".join(lines[timing_index + 1 :]).strip()
        if not body:
            continue
        cues.append(SubtitleCue(start=parse_timestamp(start_raw), end=parse_timestamp(end_raw), source_text=body))
    return cues


def to_srt(cues: list[SubtitleCue], translated: bool = True) -> str:
    blocks: list[str] = []
    render_cues = normalize_render_cues(cues, safe_gap=0.03, min_duration=0.25, translated=translated)
    for index, cue in enumerate(render_cues, start=1):
        clean_text = cue.render_text.replace(r"\N", "\n")
        blocks.append(f"{index}\n{format_timestamp(cue.start)} --> {format_timestamp(cue.end)}\n{clean_text}")
    return "\n\n".join(blocks) + ("\n" if blocks else "")


def write_srt(path: Path, cues: list[SubtitleCue], translated: bool = True) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(to_srt(cues, translated=translated), encoding="utf-8")
    return path


def to_ass(
    cues: list[SubtitleCue],
    options: RenderOptions,
    width: int = 852,
    height: int = 480,
    translated: bool = True,
) -> str:
    """Generates a complete ASS v4.00+ subtitle file with single-active movie subtitle timeline."""
    font_name = options.font_name or "Arial"
    font_size = options.font_size or 26
    margin_v = options.margin_v or 38
    outline_w = options.outline_width or 2.2
    shadow_d = options.shadow_depth or 0.8
    font_color = options.font_color or "&H00FFFFFF"
    outline_color = options.outline_color or "&H00000000"

    header = f"""[Script Info]
; Script generated by AI Video Localizer (Phase 5.1B Utterance Engine)
ScriptType: v4.00+
PlayResX: {width}
PlayResY: {height}
WrapStyle: 0
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{font_name},{font_size},{font_color},&H000000FF,{outline_color},&H80000000,-1,0,0,0,100,100,0,0,1,{outline_w},{shadow_d},2,20,20,{margin_v},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    events: list[str] = []
    engine = UtteranceEngine(
        safe_gap=options.safe_gap if hasattr(options, "safe_gap") else 0.03,
        max_line_chars=options.max_line_chars,
    )
    render_cues, _ = engine.process_cues(cues, translated=translated)

    for cue in render_cues:
        ass_text = cue.render_text.replace("{", r"\{").replace("}", r"\}")
        start_str = format_ass_timestamp(cue.start)
        end_str = format_ass_timestamp(cue.end)
        events.append(f"Dialogue: 0,{start_str},{end_str},Default,,0,0,0,,{ass_text}")

    return header + "\n".join(events) + "\n"


def write_ass(
    path: Path,
    cues: list[SubtitleCue],
    options: RenderOptions,
    width: int = 852,
    height: int = 480,
    translated: bool = True,
) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(to_ass(cues, options, width, height, translated=translated), encoding="utf-8")
    return path
